# Generated by Django 5.1.2 on 2024-12-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='api_adress',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_secretkey',
            field=models.CharField(max_length=64),
        ),
    ]
