# Generated by Django 5.1.2 on 2024-12-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectionapp', '0002_alter_api_api_adress_alter_api_api_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='api_adress',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='api',
            old_name='api_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='api',
            old_name='api_secretkey',
            new_name='secretkey',
        ),
    ]
