# Generated by Django 5.1.2 on 2024-11-29 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilkmarj', models.IntegerField()),
                ('emirorani', models.FloatField()),
                ('karal', models.FloatField()),
                ('zarardurdur', models.FloatField()),
                ('komisyon', models.FloatField()),
                ('islemertele', models.IntegerField()),
                ('optlimi', models.BooleanField(default=False)),
                ('answered', models.BooleanField(default=False)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries_by_code', to='backtest.strategy')),
                ('strategy_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtest.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
